source "https://rubygems.org"

# Specify your gem's dependencies in jordanbradleyt1a3.gemspec
gemspec

gem "rake", "~> 12.0"
gem 'rspec', '~> 3.4.0'
gem 'colorize', '~> 0.8.1'
gem 'smarter_csv', '~> 1.1.4'
gem 'tty-font', '~> 0.4.0'
gem 'tty-table', '~> 0.11.0'
gem 'tty-prompt', '~> 0.21.0'